[package]
name = "calculator"
version = "0.1.0"
license = "MIT"
edition = "2021"
repository = "https://github.com/barthofu/school"
authors = ["Bartholomé Gili <dev.bartho@gmail.com>"]

[profile.release]
strip = true
lto = true

[dependencies]
inquire = "0.6.2"